substitutions:
  device_name: "dsmr_generator"
  device_comment: "DSMR P1 Telegram generator"

esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  comment: $device_comment
  name_add_mac_suffix: false
  project:
    name: "DSMR.Generator"
    version: "1"
  platformio_options:
    board_build.flash_mode: dio

esp32:
#  board: airm2m_core_esp32c3
  board: esp32-c3-devkitm-1
  framework:
#    type: arduino
    type: esp-idf

logger: 
  baud_rate: 0

api:
  encryption:
    key: !secret esphome_api_key

ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password

  ap:
    ssid: ${device_name} AP
    password: "JxssyBpPiReF"

captive_portal:

  # Enable Web server
web_server:
  port: 80

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${device_name} - IP Address"
    ssid:
      name: "${device_name} - Wi-Fi SSID"
    bssid:
      name: "${device_name} - Wi-Fi BSSID"
  - platform: version
    name: "${device_name} - ESPHome Version"
    hide_timestamp: true

# see: https://esphome.io/components/time.html
time:
  - platform: homeassistant
#    id: homeassistant_time

## end common.yaml

uart:
  - id: P1bus
    tx_pin: TX # P1_TX
    baud_rate: 115200   # default for P1 DSMR

binary_sensor:
  - platform: gpio
    pin: 6
    name: "P1 Data request"
    id: p1_dr
    on_release:
      then:
        - uart.write: "/XMX5XMXCQA0000008879\r\n"
        - uart.write: "\r\n"
        - uart.write: "1-3:0.2.8(40)\r\n"
        - uart.write: "0-0:1.0.0(000101010000W)\r\n"
        - uart.write: "0-0:96.1.1(4530303030303030303030303030303030)\r\n"
        - uart.write: "1-0:1.8.1(000000.000*kWh)\r\n"
        - uart.write: "1-0:2.8.1(000000.000*kWh)\r\n"
        - uart.write: "1-0:1.8.2(000000.000*kWh)\r\n"
        - uart.write: "1-0:2.8.2(000000.000*kWh)\r\n"
        - uart.write: "0-0:96.14.0(0001)\r\n"
        - uart.write: "1-0:1.7.0(00.000*kW)\r\n"
        - uart.write: "1-0:2.7.0(00.000*kW)\r\n"
        - uart.write: "0-0:17.0.0(000.0*kW)\r\n"
        - uart.write: "0-0:96.3.10(1)\r\n"
        - uart.write: "0-0:96.7.21(00000)\r\n"
        - uart.write: "0-0:96.7.9(00000)\r\n"
        - uart.write: "1-0:99.97.0(0)(0-0:96.7.19)\r\n"
        - uart.write: "1-0:32.32.0(00000)\r\n"
        - uart.write: "1-0:52.32.0(00000)\r\n"
        - uart.write: "1-0:72.32.0(00000)\r\n"
        - uart.write: "1-0:32.36.0(00000)\r\n"
        - uart.write: "1-0:52.36.0(00000)\r\n"
        - uart.write: "1-0:72.36.0(00000)\r\n"
        - uart.write: "0-0:96.13.1(XMX_P1CS_V05)\r\n"
        - uart.write: "0-0:96.13.0()\r\n"
        - uart.write: "1-0:31.7.0(024*A)\r\n"
        - uart.write: "1-0:51.7.0(024*A)\r\n"
        - uart.write: "1-0:71.7.0(024*A)\r\n"
        - uart.write: "1-0:21.7.0(00.000*kW)\r\n"
        - uart.write: "1-0:41.7.0(00.000*kW)\r\n"
        - uart.write: "1-0:61.7.0(00.000*kW)\r\n"
        - uart.write: "1-0:22.7.0(00.000*kW)\r\n"
        - uart.write: "1-0:42.7.0(00.000*kW)\r\n"
        - uart.write: "1-0:62.7.0(00.000*kW)\r\n"
        - uart.write: "!19D6\r\n"

# does not work with the Luatos board, see https://github.com/esphome/issues/issues/3744
# output:
#   - platform: gpio
#     pin: 13  # D5
#     id: LedPin

#   - platform: gpio
#     pin: 12  # D4
#     id: LedPinDataRequest

button:
  - platform: template
    name: "Test P1 Telegram 20A"
    on_press:
      - uart.write: "/XMX5XMXCQA0000008879\r\n"
      - uart.write: "\r\n"
      - uart.write: "1-3:0.2.8(40)\r\n"
      - uart.write: "0-0:1.0.0(000101010000W)\r\n"
      - uart.write: "0-0:96.1.1(4530303030303030303030303030303030)\r\n"
      - uart.write: "1-0:1.8.1(000000.000*kWh)\r\n"
      - uart.write: "1-0:2.8.1(000000.000*kWh)\r\n"
      - uart.write: "1-0:1.8.2(000000.000*kWh)\r\n"
      - uart.write: "1-0:2.8.2(000000.000*kWh)\r\n"
      - uart.write: "0-0:96.14.0(0001)\r\n"
      - uart.write: "1-0:1.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:2.7.0(00.000*kW)\r\n"
      - uart.write: "0-0:17.0.0(000.0*kW)\r\n"
      - uart.write: "0-0:96.3.10(1)\r\n"
      - uart.write: "0-0:96.7.21(00000)\r\n"
      - uart.write: "0-0:96.7.9(00000)\r\n"
      - uart.write: "1-0:99.97.0(0)(0-0:96.7.19)\r\n"
      - uart.write: "1-0:32.32.0(00000)\r\n"
      - uart.write: "1-0:52.32.0(00000)\r\n"
      - uart.write: "1-0:72.32.0(00000)\r\n"
      - uart.write: "1-0:32.36.0(00000)\r\n"
      - uart.write: "1-0:52.36.0(00000)\r\n"
      - uart.write: "1-0:72.36.0(00000)\r\n"
      - uart.write: "0-0:96.13.1(XMX_P1CS_V05)\r\n"
      - uart.write: "0-0:96.13.0()\r\n"
      - uart.write: "1-0:31.7.0(020*A)\r\n"
      - uart.write: "1-0:51.7.0(020*A)\r\n"
      - uart.write: "1-0:71.7.0(020*A)\r\n"
      - uart.write: "1-0:21.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:41.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:61.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:22.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:42.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:62.7.0(00.000*kW)\r\n"
      - uart.write: "!2E16\r\n"

  - platform: template
    name: "Test P1 Telegram 40A"
    on_press:
      - uart.write: "/XMX5XMXCQA0000008879\r\n"
      - uart.write: "\r\n"
      - uart.write: "1-3:0.2.8(40)\r\n"
      - uart.write: "0-0:1.0.0(000101010000W)\r\n"
      - uart.write: "0-0:96.1.1(4530303030303030303030303030303030)\r\n"
      - uart.write: "1-0:1.8.1(000000.000*kWh)\r\n"
      - uart.write: "1-0:2.8.1(000000.000*kWh)\r\n"
      - uart.write: "1-0:1.8.2(000000.000*kWh)\r\n"
      - uart.write: "1-0:2.8.2(000000.000*kWh)\r\n"
      - uart.write: "0-0:96.14.0(0001)\r\n"
      - uart.write: "1-0:1.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:2.7.0(00.000*kW)\r\n"
      - uart.write: "0-0:17.0.0(000.0*kW)\r\n"
      - uart.write: "0-0:96.3.10(1)\r\n"
      - uart.write: "0-0:96.7.21(00000)\r\n"
      - uart.write: "0-0:96.7.9(00000)\r\n"
      - uart.write: "1-0:99.97.0(0)(0-0:96.7.19)\r\n"
      - uart.write: "1-0:32.32.0(00000)\r\n"
      - uart.write: "1-0:52.32.0(00000)\r\n"
      - uart.write: "1-0:72.32.0(00000)\r\n"
      - uart.write: "1-0:32.36.0(00000)\r\n"
      - uart.write: "1-0:52.36.0(00000)\r\n"
      - uart.write: "1-0:72.36.0(00000)\r\n"
      - uart.write: "0-0:96.13.1(XMX_P1CS_V05)\r\n"
      - uart.write: "0-0:96.13.0()\r\n"
      - uart.write: "1-0:31.7.0(040*A)\r\n"
      - uart.write: "1-0:51.7.0(040*A)\r\n"
      - uart.write: "1-0:71.7.0(040*A)\r\n"
      - uart.write: "1-0:21.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:41.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:61.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:22.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:42.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:62.7.0(00.000*kW)\r\n"
      - uart.write: "!F63B\r\n"

  - platform: template
    name: "Test P1 Telegram 41A"
    on_press:
      - uart.write: "/XMX5XMXCQA0000008879\r\n"
      - uart.write: "\r\n"
      - uart.write: "1-3:0.2.8(40)\r\n"
      - uart.write: "0-0:1.0.0(000101010000W)\r\n"
      - uart.write: "0-0:96.1.1(4530303030303030303030303030303030)\r\n"
      - uart.write: "1-0:1.8.1(000000.000*kWh)\r\n"
      - uart.write: "1-0:2.8.1(000000.000*kWh)\r\n"
      - uart.write: "1-0:1.8.2(000000.000*kWh)\r\n"
      - uart.write: "1-0:2.8.2(000000.000*kWh)\r\n"
      - uart.write: "0-0:96.14.0(0001)\r\n"
      - uart.write: "1-0:1.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:2.7.0(00.000*kW)\r\n"
      - uart.write: "0-0:17.0.0(000.0*kW)\r\n"
      - uart.write: "0-0:96.3.10(1)\r\n"
      - uart.write: "0-0:96.7.21(00000)\r\n"
      - uart.write: "0-0:96.7.9(00000)\r\n"
      - uart.write: "1-0:99.97.0(0)(0-0:96.7.19)\r\n"
      - uart.write: "1-0:32.32.0(00000)\r\n"
      - uart.write: "1-0:52.32.0(00000)\r\n"
      - uart.write: "1-0:72.32.0(00000)\r\n"
      - uart.write: "1-0:32.36.0(00000)\r\n"
      - uart.write: "1-0:52.36.0(00000)\r\n"
      - uart.write: "1-0:72.36.0(00000)\r\n"
      - uart.write: "0-0:96.13.1(XMX_P1CS_V05)\r\n"
      - uart.write: "0-0:96.13.0()\r\n"
      - uart.write: "1-0:31.7.0(041*A)\r\n"
      - uart.write: "1-0:51.7.0(041*A)\r\n"
      - uart.write: "1-0:71.7.0(041*A)\r\n"
      - uart.write: "1-0:21.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:41.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:61.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:22.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:42.7.0(00.000*kW)\r\n"
      - uart.write: "1-0:62.7.0(00.000*kW)\r\n"
      - uart.write: "!FBCB\r\n"